name: Check Signed-off-by

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  dco:
    env:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check DCO sign-off
        uses: lucacome/dco-check@v1
        with:
          fail-on-error: true
